<?php
namespace App\Controllers;
use Vedairo\Http\Request;use Vedairo\Http\Response;use App\Models\Product;use Vedairo\Validation\Validator;
class ProductController {
 public function index(Request $r):string{$q=trim((string)$r->input('q',''));$query=Product::query()->whereEq('status',1);if($q!=='')$query->whereLike('name',$q);$sort=in_array($r->input('sort'),['name','price','stock'],true)?$r->input('sort'):'id';$dir=$r->input('dir')==='asc'?'ASC':'DESC';$p=$query->orderBy($sort,$dir)->paginate((int)($r->input('per_page',10)),(int)($r->input('page',1)),'/products');ob_start();include base_path('resources/views/products/index.php');return (string) ob_get_clean();}
 public function store(Request $r):never{$v=new Validator($r->input(),['name'=>'required|min:2|max:150','price'=>'required','stock'=>'required|integer']);if(!$v->validate())Response::json(['success'=>false,'errors'=>$v->errors()],422);$id=Product::create(['name'=>$r->input('name'),'sku'=>$r->input('sku'),'price'=>(float)$r->input('price'),'stock'=>(int)$r->input('stock'),'status'=>1,'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')]);if($r->wantsJson())Response::json(['success'=>true,'id'=>$id],201);redirect('/products');}
 public function update(Request $r,string $id):never{$v=new Validator($r->input(),['name'=>'required|min:2|max:150','price'=>'required','stock'=>'required|integer']);if(!$v->validate())Response::json(['success'=>false,'errors'=>$v->errors()],422);Product::updateById((int)$id,['name'=>$r->input('name'),'sku'=>$r->input('sku'),'price'=>(float)$r->input('price'),'stock'=>(int)$r->input('stock'),'updated_at'=>date('Y-m-d H:i:s')]);Response::json(['success'=>true]);}
 public function destroy(Request $r,string $id):never{Product::deleteById((int)$id);Response::json(['success'=>true]);}
 public function apiIndex(Request $r):never{$q=trim((string)$r->input('q',''));$query=Product::query();if($q!=='')$query->whereLike('name',$q);$p=$query->orderBy('id','DESC')->paginate((int)$r->input('per_page',20),(int)$r->input('page',1),'/api/v1/products');Response::json(['success'=>true,'data'=>$p->items,'meta'=>['page'=>$p->page,'per_page'=>$p->perPage,'total'=>$p->total,'last_page'=>$p->lastPage()]]);}
}
